global:
  scrape_interval: 1m

# Set default port for scrapping
scrape_configs:
  - job_name: 'mach-operator'
    scrape_interval: 1m
    static_configs:
      - targets: ['mach-operator-node:9092']

  - job_name: 'mach-verifier'
    scrape_interval: 1m
    static_configs:
      - targets: ['mach-operator-verifier:9094']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']