method: "confirmAlert"

generic_operator_addr: http://mach-avs-ethereum-generic-operator:8901

rpc_cfg:
  rpc_addr: 0.0.0.0:8902
  rpc_vhosts: ["*", "localhost"]
  rpc_cors: ["*", "localhost"]

chain_ids:
  optimism: 10
  arbitrum_one: 42161

work_proofs_mod:
  optimism: 900
  arbitrum_one: 9000